// Breed data for SEO landing pages
// Each breed gets its own page: /breeds/[slug]

export interface Breed {
  slug: string;
  name: string;
  type: "dog" | "cat";
  emoji: string;
  description: string;
  traits: string[];
  popularStyles: string[]; // style values from constants.ts
}

export const DOG_BREEDS: Breed[] = [
  { slug: "golden-retriever", name: "Golden Retriever", type: "dog", emoji: "🦮", description: "The golden coat, warm eyes, and gentle smile — AI captures every strand of that iconic fur.", traits: ["golden coat", "warm brown eyes", "friendly expression", "feathered tail"], popularStyles: ["realistic-studio", "royal-portrait", "cartoon-pixar"] },
  { slug: "labrador", name: "Labrador Retriever", type: "dog", emoji: "🐕", description: "Whether chocolate, yellow, or black — your Lab's loyal personality shines through every portrait.", traits: ["muscular build", "otter tail", "kind eyes", "broad head"], popularStyles: ["action-outdoor", "realistic-studio", "superhero"] },
  { slug: "french-bulldog", name: "French Bulldog", type: "dog", emoji: "🐶", description: "Those bat ears, wrinkled face, and compact charm — perfectly preserved in every style.", traits: ["bat ears", "flat face", "compact body", "wrinkled forehead"], popularStyles: ["cartoon-pixar", "royal-portrait", "cozy-holiday"] },
  { slug: "german-shepherd", name: "German Shepherd", type: "dog", emoji: "🐕‍🦺", description: "Noble, powerful, and intelligent — your GSD's commanding presence deserves a portrait to match.", traits: ["tan and black coat", "pointed ears", "noble stance", "intelligent eyes"], popularStyles: ["superhero", "realistic-studio", "royal-portrait"] },
  { slug: "poodle", name: "Poodle", type: "dog", emoji: "🐩", description: "Elegant, curly, and impossibly photogenic — every curl captured in stunning detail.", traits: ["curly coat", "elegant build", "intelligent expression", "proud stance"], popularStyles: ["royal-portrait", "watercolor", "realistic-studio"] },
  { slug: "bulldog", name: "Bulldog", type: "dog", emoji: "🐶", description: "Wrinkles, underbite, and pure charm — your Bulldog's personality pops in every style.", traits: ["wrinkled face", "underbite", "stocky build", "pushed-in nose"], popularStyles: ["superhero", "cartoon-pixar", "royal-portrait"] },
  { slug: "beagle", name: "Beagle", type: "dog", emoji: "🐕", description: "Those soulful eyes and floppy ears — AI preserves the beagle charm that melts hearts.", traits: ["tricolor coat", "floppy ears", "soulful eyes", "compact body"], popularStyles: ["watercolor", "action-outdoor", "cartoon-pixar"] },
  { slug: "husky", name: "Siberian Husky", type: "dog", emoji: "🐺", description: "Striking blue eyes, wolf-like features, and that thick double coat — pure drama in every portrait.", traits: ["blue or heterochromia eyes", "wolf-like face", "thick double coat", "erect ears"], popularStyles: ["action-outdoor", "anime-ghibli", "superhero"] },
  { slug: "dachshund", name: "Dachshund", type: "dog", emoji: "🌭", description: "Long body, short legs, and endless personality — your wiener dog in glorious art.", traits: ["elongated body", "short legs", "floppy ears", "alert expression"], popularStyles: ["cartoon-pixar", "cozy-holiday", "royal-portrait"] },
  { slug: "corgi", name: "Corgi", type: "dog", emoji: "🐕", description: "That fluffy butt, short legs, and royal attitude — corgis were born for portraits.", traits: ["short legs", "fox-like face", "fluffy rear", "pointed ears"], popularStyles: ["royal-portrait", "cartoon-pixar", "anime-ghibli"] },
  { slug: "yorkshire-terrier", name: "Yorkshire Terrier", type: "dog", emoji: "🐶", description: "Tiny but fierce — your Yorkie's silky coat and big personality shine in every style.", traits: ["silky coat", "tiny size", "perky ears", "confident stance"], popularStyles: ["royal-portrait", "cozy-holiday", "watercolor"] },
  { slug: "boxer", name: "Boxer", type: "dog", emoji: "🐶", description: "Muscular, playful, and always goofy — your Boxer's energy captured forever.", traits: ["muscular build", "square jaw", "fawn or brindle coat", "playful expression"], popularStyles: ["superhero", "action-outdoor", "cartoon-pixar"] },
  { slug: "rottweiler", name: "Rottweiler", type: "dog", emoji: "🐕‍🦺", description: "Powerful and loyal — your Rottweiler's protective presence in stunning portrait form.", traits: ["black and tan markings", "broad chest", "powerful build", "confident gaze"], popularStyles: ["superhero", "realistic-studio", "royal-portrait"] },
  { slug: "shih-tzu", name: "Shih Tzu", type: "dog", emoji: "🐶", description: "That flowing coat and sweet face — your Shih Tzu is royalty and they know it.", traits: ["long flowing coat", "flat face", "large round eyes", "small build"], popularStyles: ["royal-portrait", "cozy-holiday", "watercolor"] },
  { slug: "doberman", name: "Doberman Pinscher", type: "dog", emoji: "🐕", description: "Sleek, athletic, and commanding — your Doberman's elegance in portrait form.", traits: ["sleek coat", "athletic build", "cropped or natural ears", "rust markings"], popularStyles: ["superhero", "realistic-studio", "royal-portrait"] },
  { slug: "pomeranian", name: "Pomeranian", type: "dog", emoji: "🐶", description: "A fluffy cloud with attitude — your Pom's fox-like face and plush coat in AI art.", traits: ["fluffy double coat", "fox-like face", "tiny size", "alert expression"], popularStyles: ["cartoon-pixar", "anime-ghibli", "royal-portrait"] },
  { slug: "great-dane", name: "Great Dane", type: "dog", emoji: "🐕", description: "Gentle giant — your Dane's majestic size and sweet nature in every portrait style.", traits: ["massive size", "long legs", "gentle expression", "various coat patterns"], popularStyles: ["royal-portrait", "superhero", "realistic-studio"] },
  { slug: "chihuahua", name: "Chihuahua", type: "dog", emoji: "🐶", description: "Small body, enormous personality — your Chihuahua's sass immortalized in art.", traits: ["tiny size", "apple head", "large eyes", "perky ears"], popularStyles: ["cartoon-pixar", "superhero", "cozy-holiday"] },
  { slug: "australian-shepherd", name: "Australian Shepherd", type: "dog", emoji: "🐕", description: "Merle coat, bright eyes, and boundless energy — your Aussie's unique patterns preserved perfectly.", traits: ["merle coat pattern", "bright blue or heterochromia eyes", "medium build", "intelligent expression"], popularStyles: ["action-outdoor", "anime-ghibli", "watercolor"] },
  { slug: "cavalier-king-charles", name: "Cavalier King Charles Spaniel", type: "dog", emoji: "🐶", description: "Those big round eyes and silky ears — pure elegance in every portrait.", traits: ["silky ears", "large round eyes", "gentle expression", "tricolor or blenheim coat"], popularStyles: ["royal-portrait", "watercolor", "cozy-holiday"] },
  { slug: "bernese-mountain-dog", name: "Bernese Mountain Dog", type: "dog", emoji: "🐕", description: "Tricolor beauty with a gentle soul — your Berner's majestic presence in stunning art.", traits: ["tricolor coat", "large build", "gentle eyes", "fluffy fur"], popularStyles: ["action-outdoor", "cozy-holiday", "realistic-studio"] },
  { slug: "pitbull", name: "Pit Bull", type: "dog", emoji: "🐶", description: "Muscular, loyal, and misunderstood — show the world your Pittie's true sweet nature.", traits: ["muscular build", "broad head", "wide smile", "short coat"], popularStyles: ["superhero", "cartoon-pixar", "realistic-studio"] },
  { slug: "border-collie", name: "Border Collie", type: "dog", emoji: "🐕", description: "The smartest dog in the room — your Border Collie's intense gaze and agility captured.", traits: ["black and white coat", "intense herding gaze", "medium build", "feathered tail"], popularStyles: ["action-outdoor", "anime-ghibli", "realistic-studio"] },
  { slug: "maltese", name: "Maltese", type: "dog", emoji: "🐶", description: "Pure white elegance — your Maltese's silky coat flows beautifully in every style.", traits: ["pure white coat", "silky long fur", "dark eyes", "tiny size"], popularStyles: ["royal-portrait", "watercolor", "cozy-holiday"] },
  { slug: "samoyed", name: "Samoyed", type: "dog", emoji: "☁️", description: "The smiling cloud dog — your Sammy's fluffy white coat and signature smile in art.", traits: ["fluffy white coat", "signature smile", "dark eyes", "curled tail"], popularStyles: ["anime-ghibli", "cozy-holiday", "cartoon-pixar"] },
];

export const CAT_BREEDS: Breed[] = [
  { slug: "persian", name: "Persian Cat", type: "cat", emoji: "🐱", description: "Flat face, flowing coat, and regal attitude — your Persian was born for portraits.", traits: ["flat face", "long flowing coat", "large round eyes", "stocky build"], popularStyles: ["royal-portrait", "watercolor", "cozy-holiday"] },
  { slug: "siamese", name: "Siamese Cat", type: "cat", emoji: "🐱", description: "Striking blue eyes and color points — your Siamese's elegance captured in AI art.", traits: ["blue almond eyes", "color point markings", "sleek body", "wedge-shaped head"], popularStyles: ["anime-ghibli", "realistic-studio", "royal-portrait"] },
  { slug: "maine-coon", name: "Maine Coon", type: "cat", emoji: "🦁", description: "The gentle giant of cats — your Maine Coon's majestic mane and tufted ears in stunning detail.", traits: ["large size", "tufted ears", "bushy tail", "lion-like mane"], popularStyles: ["royal-portrait", "superhero", "realistic-studio"] },
  { slug: "ragdoll", name: "Ragdoll Cat", type: "cat", emoji: "🐱", description: "Blue eyes, fluffy coat, and the most relaxed cat alive — your Ragdoll in portrait form.", traits: ["bright blue eyes", "semi-long silky coat", "color point pattern", "large build"], popularStyles: ["cozy-holiday", "watercolor", "anime-ghibli"] },
  { slug: "british-shorthair", name: "British Shorthair", type: "cat", emoji: "🐱", description: "Round face, plush coat, and that signature dignified stare — your British Shorthair is art.", traits: ["round face", "dense plush coat", "copper eyes", "stocky build"], popularStyles: ["royal-portrait", "cartoon-pixar", "realistic-studio"] },
  { slug: "bengal", name: "Bengal Cat", type: "cat", emoji: "🐆", description: "Wild leopard patterns in a domestic package — your Bengal's exotic markings preserved perfectly.", traits: ["spotted or marbled coat", "muscular build", "wild appearance", "glittering fur"], popularStyles: ["action-outdoor", "superhero", "anime-ghibli"] },
  { slug: "scottish-fold", name: "Scottish Fold", type: "cat", emoji: "🐱", description: "Those folded ears and owl-like face — your Scottish Fold's unique charm in every style.", traits: ["folded ears", "round face", "large round eyes", "compact body"], popularStyles: ["cartoon-pixar", "cozy-holiday", "anime-ghibli"] },
  { slug: "sphynx", name: "Sphynx Cat", type: "cat", emoji: "🐱", description: "Hairless, wrinkled, and absolutely unforgettable — your Sphynx's alien beauty in art.", traits: ["hairless", "wrinkled skin", "large ears", "lemon-shaped eyes"], popularStyles: ["superhero", "anime-ghibli", "royal-portrait"] },
  { slug: "russian-blue", name: "Russian Blue", type: "cat", emoji: "🐱", description: "Silver-blue coat and emerald eyes — your Russian Blue's mysterious elegance captured.", traits: ["blue-gray coat", "green eyes", "sleek body", "gentle expression"], popularStyles: ["realistic-studio", "watercolor", "royal-portrait"] },
  { slug: "abyssinian", name: "Abyssinian Cat", type: "cat", emoji: "🐱", description: "Ticked coat and wildcat energy — your Aby's athletic grace in stunning portraits.", traits: ["ticked coat", "almond eyes", "lean athletic build", "large ears"], popularStyles: ["action-outdoor", "anime-ghibli", "superhero"] },
  { slug: "tabby", name: "Tabby Cat", type: "cat", emoji: "🐱", description: "Classic stripes, spots, or swirls — every tabby is unique and deserves a portrait.", traits: ["striped or spotted pattern", "M-shaped forehead marking", "various colors", "expressive eyes"], popularStyles: ["watercolor", "cozy-holiday", "cartoon-pixar"] },
  { slug: "tuxedo", name: "Tuxedo Cat", type: "cat", emoji: "🐱", description: "Black and white and always dressed to impress — your tuxedo cat's formal elegance.", traits: ["black and white bicolor", "formal appearance", "various builds", "bright eyes"], popularStyles: ["royal-portrait", "superhero", "cartoon-pixar"] },
  { slug: "orange-tabby", name: "Orange Tabby", type: "cat", emoji: "🧡", description: "That warm orange glow and one shared brain cell — your ginger cat immortalized.", traits: ["orange striped coat", "warm coloring", "often large build", "friendly expression"], popularStyles: ["cozy-holiday", "cartoon-pixar", "anime-ghibli"] },
  { slug: "calico", name: "Calico Cat", type: "cat", emoji: "🐱", description: "Three colors, infinite beauty — your calico's unique patchwork in stunning AI art.", traits: ["tri-color patches", "white/orange/black", "unique pattern", "various builds"], popularStyles: ["watercolor", "anime-ghibli", "realistic-studio"] },
  { slug: "black-cat", name: "Black Cat", type: "cat", emoji: "🐈‍⬛", description: "Sleek, mysterious, and gorgeous — your black cat's beauty finally captured properly.", traits: ["solid black coat", "golden or green eyes", "sleek build", "mysterious aura"], popularStyles: ["superhero", "anime-ghibli", "royal-portrait"] },
];

export const ALL_BREEDS = [...DOG_BREEDS, ...CAT_BREEDS];

export function getBreedBySlug(slug: string): Breed | undefined {
  return ALL_BREEDS.find((b) => b.slug === slug);
}
